settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: local_development
  path: .
  commands:
    install:
      status: true
      method: go build -o local_development api/cmd/local_development.go
    run:
      status: true
      method: ./local_development
  watcher:
    extensions:
    - go
    paths:
    - ./api
    ignored_paths:
    - .git
    - .realize
    - vendor
