settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: local_development
  path: .
  commands:
    install:
      status: true
      method: go build -o main api/cmd/local_development/main.go
    run:
      status: true
      method: ./main
  watcher:
    extensions:
    - go
    paths:
    - ./api
    ignored_paths:
    - .git
    - .realize
    - vendor
