version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    networks:
      - shalust-network

networks:
  shalust-network:
    external: true
