version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=[mysql]
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=shalust
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    networks:
      - shalust-network

networks:
  shalust-network:
    external: true
