settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: local_development
  path: .
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignored_paths:
    - .git
    - .realize
    - vendor
